# Generated by Django 2.2.7 on 2021-03-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('orcid', models.CharField(max_length=16)),
                ('institution', models.CharField(max_length=400)),
                ('project_title', models.CharField(max_length=400)),
                ('project_description', models.TextField()),
                ('positive_samples', models.PositiveIntegerField()),
                ('negative_samples', models.PositiveIntegerField()),
                ('sample_information', models.TextField()),
            ],
        ),
    ]
