# Generated by Django 2.2.7 on 2021-03-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Order',
        ),
    ]
