# Generated by Django 2.2.7 on 2021-04-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210321_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_results', models.TextField()),
                ('sample_type', models.TextField()),
                ('test_type', models.TextField()),
                ('test_dates', models.DateField()),
                ('collection_site', models.TextField()),
                ('user_id', models.PositiveIntegerField()),
                ('ct_values', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
