# Generated by Django 2.2.7 on 2021-04-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='ct_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='samples',
            name='test_dates',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='samples',
            name='user_id',
            field=models.TextField(),
        ),
    ]
