# Generated by Django 2.2.7 on 2021-04-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210401_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='ct_values',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='samples',
            name='test_dates',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='samples',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
    ]
