# Generated by Django 2.2.7 on 2021-04-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samples',
            old_name='sample_id',
            new_name='user_id',
        ),
    ]
