# Generated by Django 2.2.7 on 2021-04-15 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210413_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Researcher'),
        ),
    ]
