# Generated by Django 2.2.7 on 2021-04-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210414_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_request',
            field=models.DateField(),
        ),
    ]
