# Generated by Django 2.2.7 on 2021-04-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210414_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_request',
            field=models.DateField(auto_now_add=True),
        ),
    ]
