# Generated by Django 2.2.7 on 2021-04-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210414_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rna_extraction',
            field=models.TextField(blank=True),
        ),
    ]
