# Generated by Django 2.2.7 on 2021-04-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_order_rna_extraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rna_extraction',
            new_name='RNA_extraction',
        ),
    ]
