# Generated by Django 2.2.7 on 2021-04-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_researcher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
